package repository

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/jmoiron/sqlx"
	"github.com/RakeshAero/taskflow-rakeshbalu/backend/internal/models"
)

// UserRepository handles all DB queries for the users table.
// No business logic lives here — just SQL in, struct out.
type UserRepository struct {
	db *sqlx.DB
}

func NewUserRepository(db *sqlx.DB) *UserRepository {
	return &UserRepository{db: db}
}

// ── Sentinel errors ───────────────────────────────────────────────────────────
// Handlers check for these specific errors to decide which HTTP status to return.
// Using named errors (instead of strings) means the compiler catches typos.
var (
	ErrNotFound      = errors.New("not found")
	ErrEmailTaken    = errors.New("email already in use")
)

// CreateUser inserts a new user row and returns the full created record.
// The password field must already be a bcrypt hash — this function
// does NOT hash; that responsibility belongs to the auth handler.
//
// Returns ErrEmailTaken if the email violates the unique index.
func (r *UserRepository) CreateUser(ctx context.Context, name, email, hashedPassword string) (*models.User, error) {
	// RETURNING * tells Postgres to send back the inserted row, including
	// the id and created_at that were generated by the DB defaults.
	// sqlx.Get scans the single returned row directly into the User struct.
	query := `
		INSERT INTO users (name, email, password)
		VALUES ($1, $2, $3)
		RETURNING *`

	var user models.User
	err := r.db.GetContext(ctx, &user, query, name, email, hashedPassword)
	if err != nil {
		// Postgres error code 23505 = unique_violation.
		// We check for this specifically so the handler can return 409/400
		// with a helpful "email already in use" message instead of a generic 500.
		if isUniqueViolation(err) {
			return nil, ErrEmailTaken
		}
		return nil, fmt.Errorf("CreateUser: %w", err)
	}

	return &user, nil
}

// GetUserByEmail finds a user by email address.
// Used by the login handler to look up the account before comparing passwords.
//
// Returns ErrNotFound if no row matches — handler maps this to 401
// (we never confirm whether an email exists to prevent user enumeration).
func (r *UserRepository) GetUserByEmail(ctx context.Context, email string) (*models.User, error) {
	query := `SELECT * FROM users WHERE email = $1 LIMIT 1`

	var user models.User
	err := r.db.GetContext(ctx, &user, query, email)
	if err != nil {
		// sql.ErrNoRows is the standard "no matching row" error from database/sql.
		// sqlx wraps it so we check with errors.Is().
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("GetUserByEmail: %w", err)
	}

	return &user, nil
}

// GetUserByID fetches a user by their UUID primary key.
// Used by the JWT middleware to verify the token's user_id still exists.
func (r *UserRepository) GetUserByID(ctx context.Context, id string) (*models.User, error) {
	query := `SELECT * FROM users WHERE id = $1 LIMIT 1`

	var user models.User
	err := r.db.GetContext(ctx, &user, query, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("GetUserByID: %w", err)
	}

	return &user, nil
}